# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'mianjizhushou' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mianjizhushou
  pod 'Alamofire', '~> 5.5'

  target 'mianjizhushouTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mianjizhushouUITests' do
    # Pods for testing
  end

end
