# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'taobao_baichuan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for taobao_baichuan

  pod 'miniAppMediaSDK', '0.0.1.45-BC3'
  pod 'mtopSDK', '3.0.0.5-BC1'
  pod 'AliLinkPartnerSDK', '4.0.0.24-BC1'
  pod 'MunionBcAdSDK', '1.0.5-BC1'
  pod 'AlibcTradeUltimateSDK', '5.0.0.7'
  pod 'Triver', '1.0.11.5-BC7'
  pod 'Windmill', '1.3.7.3-BC3'

  target 'taobao_baichuanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'taobao_baichuanUITests' do
    # Pods for testing
  end

end
