# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
target 'LayoutDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LayoutDemo
  pod 'Alamofire', '~> 5.5'

  target 'LayoutDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LayoutDemoUITests' do
    # Pods for testing
  end

end
